export const invalidMailText = "Почта невалидна";
export const invalidPasswordText = "Пароль ненадежен";
export const notMatchingPasswordText = "Пароль должен совпадать";
export const passwordChangedText = "Пароль успешно обновлен";
export const mailNotRegistredText = (mail?: string) => `Почта ${mail} не зарегистрирована`;
export const mailVerifySentText = (mail?: string) => `На почту ${mail} отправлено письмо с дальнейшей инструкцией`;
export const mailVerifiedText = "Почта успешно подтверждена";
export const invalidEmptyText = "Это поле не может быть пустым";
export const invalidPriceText = "Цена должна быть числом больше нуля";
export const emptyUserText = "Аноним";
export const invalidProfileId = "Это поле должно содержать ссылку на исполнителя, или быть пустым";
